databases:
  - name: backend_dev
    databaseName: backend_dev
    user: backend_dev_user

services:
  - type: web
    name: test
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: backend_dev
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false